dist: trusty
language: cpp

script:
 - mkdir build && cd build
 - cmake ..
 - cmake --build .
 - ./hello
 
env:
 - COMPILER=g++-6

addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
  packages:
   - g++-6