dist: trusty
language: cpp

script:
 - mkdir build && cd build
 - cmake ..
 - cmake --build .
 - ./hello
 
env:
 - BUILD_TYPE=Release COMPILER=g++-4.9
 - BUILD_TYPE=Release COMPILER=g++-5
 - BUILD_TYPE=Release COMPILER=g++-6
 - BUILD_TYPE=Release COMPILER=clang++-3.9
 - BUILD_TYPE=Release COMPILER=clang++-4.0
 - BUILD_TYPE=Debug COMPILER=g++-4.9
 - BUILD_TYPE=Debug COMPILER=g++-5
 - BUILD_TYPE=Debug COMPILER=g++-6
 - BUILD_TYPE=Debug COMPILER=clang++-3.9
 - BUILD_TYPE=Debug COMPILER=clang++-4.0